spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres

    hikari:
      maximumPoolSize: 50

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.web:  DEBUG

server:
  port: 8081